// AUTO-GENERATED by scripts/generate-methods.ts — do not edit
import type { paths, components } from "./schema.js";
import type createFetchClient from "openapi-fetch";

type Client = ReturnType<typeof createFetchClient<paths>>;

// Extract the JSON request body type from an operation path+method
type ReqBody<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends { requestBody: { content: { "application/json": infer B } } } ? B : never;

// Extract the success response type
type ResBody<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends { responses: { 200: { content: { "application/json": infer R } } } } ? R : paths[P][M] extends { responses: { 201: { content: { "application/json": infer R } } } } ? R : paths[P][M] extends { responses: { 202: { content: { "application/json": infer R } } } } ? R : unknown;

// Extract query parameters
type QueryParams<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends { parameters: { query?: infer Q } } ? Q : never;

export interface VidJutsuMethods {
  /** Create account Auth required. */
  createAccount(body: ReqBody<"/v1/accounts", "post">): ReturnType<Client["POST"]>;
  /** Update account Auth required. */
  updateAccount(body: ReqBody<"/v1/accounts", "put">, query?: QueryParams<"/v1/accounts", "put">): ReturnType<Client["PUT"]>;
  /** List accounts or get by ID Auth required. */
  listOrGetAccounts(query?: QueryParams<"/v1/accounts", "get">): ReturnType<Client["GET"]>;
  /** Delete account Auth required. */
  deleteAccount(query?: QueryParams<"/v1/accounts", "delete">): ReturnType<Client["DELETE"]>;
  /** Recover API key Public endpoint. */
  recoverApiKey(body: ReqBody<"/v1/api_keys/recover", "post">): ReturnType<Client["POST"]>;
  /** Rotate API key Auth required. */
  rotateApiKey(): ReturnType<Client["POST"]>;
  /** Create asset from existing URL Auth required. */
  createAsset(body: ReqBody<"/v1/assets", "post">): ReturnType<Client["POST"]>;
  /** Update asset metadata Auth required. */
  updateAsset(body: ReqBody<"/v1/assets", "put">, query?: QueryParams<"/v1/assets", "put">): ReturnType<Client["PUT"]>;
  /** List assets or get by ID Auth required. */
  listOrGetAssets(query?: QueryParams<"/v1/assets", "get">): ReturnType<Client["GET"]>;
  /** Delete asset (soft) Auth required. */
  deleteAsset(query?: QueryParams<"/v1/assets", "delete">): ReturnType<Client["DELETE"]>;
  /** Agent registration (auth.md) */
  signupAgent(body: ReqBody<"/v1/auth/agent", "post">): ReturnType<Client["POST"]>;
  /** Initiate claim flow */
  agentClaim(body: ReqBody<"/v1/auth/agent/claim", "post">): ReturnType<Client["POST"]>;
  /** Complete claim flow */
  agentClaimComplete(body: ReqBody<"/v1/auth/agent/claim/complete", "post">): ReturnType<Client["POST"]>;
  /** Revoke credential */
  agentRevoke(): ReturnType<Client["POST"]>;
  /** Confirm email verification code Public endpoint. */
  confirmVerification(body: ReqBody<"/v1/auth/verify/confirm", "post">): ReturnType<Client["POST"]>;
  /** Request email verification code Public endpoint. */
  requestVerification(body: ReqBody<"/v1/auth/verify/request", "post">): ReturnType<Client["POST"]>;
  /** Check spec Auth required. 5 credits. */
  checkSpec(body: ReqBody<"/v1/check", "post">): ReturnType<Client["POST"]>;
  /** Get check rules Auth required. */
  getCheckRules(): ReturnType<Client["GET"]>;
  /** Update check rules Auth required. */
  updateCheckRules(body: ReqBody<"/v1/check/rules", "put">): ReturnType<Client["PUT"]>;
  /** Create a B-roll-treated clip artifact Auth required. */
  addClipBroll(body: ReqBody<"/v1/clips/broll", "post">): ReturnType<Client["POST"]>;
  /** Create a captioned clip artifact Auth required. */
  addClipCaptions(body: ReqBody<"/v1/clips/captions", "post">): ReturnType<Client["POST"]>;
  /** Generate a bounded batch of 9:16 clips from a video source or video ID Auth required. */
  generateClips(body: ReqBody<"/v1/clips/generate", "post">): ReturnType<Client["POST"]>;
  /** Check prompt compliance */
  checkCompliancePrompt(body: ReqBody<"/v1/compliance/prompt", "post">): ReturnType<Client["POST"]>;
  /** Check video compliance */
  checkComplianceVideo(body: ReqBody<"/v1/compliance/video", "post">): ReturnType<Client["POST"]>;
  /** Check checkout status Public endpoint. */
  getCheckoutStatus(query?: QueryParams<"/v1/credits/status", "get">): ReturnType<Client["GET"]>;
  /** Burn fine-print disclaimer onto video */
  createDisclaimer(body: ReqBody<"/v1/disclaimer", "post">): ReturnType<Client["POST"]>;
  /** List generated clips or get one by ID Auth required. */
  listOrGetDistributionClips(query?: QueryParams<"/v1/distribution/clips", "get">): ReturnType<Client["GET"]>;
  /** Inspect a distribution job Auth required. */
  getDistributionJob(query?: QueryParams<"/v1/distribution/jobs", "get">): ReturnType<Client["GET"]>;
  /** Extract from media Auth required. 5 credits. */
  extractMedia(body: ReqBody<"/v1/extract", "post">): ReturnType<Client["POST"]>;
  /** API info Public endpoint. */
  getInfo(): ReturnType<Client["GET"]>;
  /** Inspect a durable VidJutsu media job Auth required. */
  getJob(query?: QueryParams<"/v1/jobs", "get">): ReturnType<Client["GET"]>;
  /** Burn text overlay onto video Auth required. 5 credits. */
  createOverlay(body: ReqBody<"/v1/overlay", "post">): ReturnType<Client["POST"]>;
  /** Create post Auth required. */
  createPost(body: ReqBody<"/v1/posts", "post">): ReturnType<Client["POST"]>;
  /** Update post Auth required. */
  updatePost(body: ReqBody<"/v1/posts", "put">, query?: QueryParams<"/v1/posts", "put">): ReturnType<Client["PUT"]>;
  /** List posts or get by ID Auth required. */
  listOrGetPosts(query?: QueryParams<"/v1/posts", "get">): ReturnType<Client["GET"]>;
  /** Delete post Auth required. */
  deletePost(query?: QueryParams<"/v1/posts", "delete">): ReturnType<Client["DELETE"]>;
  /** Get pricing Public endpoint. */
  getPricing(): ReturnType<Client["GET"]>;
  /** Create editor project */
  createEditorProject(body: ReqBody<"/v1/projects", "post">): ReturnType<Client["POST"]>;
  /** Update editor project */
  updateEditorProject(body: ReqBody<"/v1/projects", "put">, query?: QueryParams<"/v1/projects", "put">): ReturnType<Client["PUT"]>;
  /** List projects or get by ID */
  listOrGetEditorProjects(query?: QueryParams<"/v1/projects", "get">): ReturnType<Client["GET"]>;
  /** Archive editor project (soft) */
  deleteEditorProject(query?: QueryParams<"/v1/projects", "delete">): ReturnType<Client["DELETE"]>;
  /** Create reference Auth required. */
  createReference(body: ReqBody<"/v1/references", "post">): ReturnType<Client["POST"]>;
  /** Update reference Auth required. */
  updateReference(body: ReqBody<"/v1/references", "put">, query?: QueryParams<"/v1/references", "put">): ReturnType<Client["PUT"]>;
  /** List references or get by ID Auth required. */
  listOrGetReferences(query?: QueryParams<"/v1/references", "get">): ReturnType<Client["GET"]>;
  /** Delete reference Auth required. */
  deleteReference(query?: QueryParams<"/v1/references", "delete">): ReturnType<Client["DELETE"]>;
  /** Scrape Instagram post or reel Auth required. 1 credits. */
  scrapeInstagramPost(body: ReqBody<"/v1/scrape/instagram/post", "post">): ReturnType<Client["POST"]>;
  /** Scrape Instagram post comments Auth required. 1 credits. */
  scrapeInstagramPostComments(body: ReqBody<"/v1/scrape/instagram/post/comments", "post">): ReturnType<Client["POST"]>;
  /** Scrape Instagram profile Auth required. 1 credits. */
  scrapeInstagramProfile(body: ReqBody<"/v1/scrape/instagram/profile", "post">): ReturnType<Client["POST"]>;
  /** Scrape Instagram user posts Auth required. 1 credits. */
  scrapeInstagramUserPosts(body: ReqBody<"/v1/scrape/instagram/user/posts", "post">): ReturnType<Client["POST"]>;
  /** Scrape Instagram user reels Auth required. 1 credits. */
  scrapeInstagramUserReels(body: ReqBody<"/v1/scrape/instagram/user/reels", "post">): ReturnType<Client["POST"]>;
  /** Scrape TikTok profile Auth required. 1 credits. */
  scrapeTikTokProfile(body: ReqBody<"/v1/scrape/tiktok/profile", "post">): ReturnType<Client["POST"]>;
  /** Scrape TikTok profile videos Auth required. 1 credits. */
  scrapeTikTokProfileVideos(body: ReqBody<"/v1/scrape/tiktok/profile/videos", "post">): ReturnType<Client["POST"]>;
  /** Scrape TikTok user search Auth required. 1 credits. */
  scrapeTikTokSearchUsers(body: ReqBody<"/v1/scrape/tiktok/search/users", "post">): ReturnType<Client["POST"]>;
  /** Scrape TikTok trending feed Auth required. 1 credits. */
  scrapeTikTokTrending(body: ReqBody<"/v1/scrape/tiktok/trending", "post">): ReturnType<Client["POST"]>;
  /** Scrape TikTok video Auth required. 1 credits. */
  scrapeTikTokVideo(body: ReqBody<"/v1/scrape/tiktok/video", "post">): ReturnType<Client["POST"]>;
  /** Scrape TikTok video comments Auth required. 1 credits. */
  scrapeTikTokVideoComments(body: ReqBody<"/v1/scrape/tiktok/video/comments", "post">): ReturnType<Client["POST"]>;
  /** Scrape TikTok video transcript Auth required. 1 credits. */
  scrapeTikTokVideoTranscript(body: ReqBody<"/v1/scrape/tiktok/video/transcript", "post">): ReturnType<Client["POST"]>;
  /** Create subscription Public endpoint. */
  createSubscription(body: ReqBody<"/v1/subscribe", "post">): ReturnType<Client["POST"]>;
  /** Transcribe media Auth required. 10 credits. */
  transcribeMedia(body: ReqBody<"/v1/transcribe", "post">): ReturnType<Client["POST"]>;
  /** Upload file Auth required. */
  uploadFile(): ReturnType<Client["POST"]>;
  /** Upload from URL Auth required. */
  uploadFromUrl(body: ReqBody<"/v1/upload/url", "post">): ReturnType<Client["POST"]>;
  /** Get daily usage */
  getUsage(): ReturnType<Client["GET"]>;
  /** Add a video from an uploaded asset or direct MP4 URL Auth required. */
  addVideo(body: ReqBody<"/v1/videos/add", "post">): ReturnType<Client["POST"]>;
  /** Import an Instagram video into VidJutsu Auth required. 1 credits. */
  downloadInstagramVideo(body: ReqBody<"/v1/videos/download/instagram", "post">): ReturnType<Client["POST"]>;
  /** Import a TikTok video into VidJutsu Auth required. 1 credits. */
  downloadTikTokVideo(body: ReqBody<"/v1/videos/download/tiktok", "post">): ReturnType<Client["POST"]>;
  /** Watch media Auth required. 10 credits. */
  watchMedia(body: ReqBody<"/v1/watch", "post">): ReturnType<Client["POST"]>;
}

export function bindMethods(client: Client): VidJutsuMethods {
  return {
    createAccount(body) {
      return client.POST("/v1/accounts" as any, { body } as any);
    },
    updateAccount(body, query) {
      return client.PUT("/v1/accounts" as any, { body, params: { query } } as any);
    },
    listOrGetAccounts(query) {
      return client.GET("/v1/accounts" as any, { params: { query } } as any);
    },
    deleteAccount(query) {
      return client.DELETE("/v1/accounts" as any, { params: { query } } as any);
    },
    recoverApiKey(body) {
      return client.POST("/v1/api_keys/recover" as any, { body } as any);
    },
    rotateApiKey() {
      return client.POST("/v1/api_keys/rotate" as any, {} as any);
    },
    createAsset(body) {
      return client.POST("/v1/assets" as any, { body } as any);
    },
    updateAsset(body, query) {
      return client.PUT("/v1/assets" as any, { body, params: { query } } as any);
    },
    listOrGetAssets(query) {
      return client.GET("/v1/assets" as any, { params: { query } } as any);
    },
    deleteAsset(query) {
      return client.DELETE("/v1/assets" as any, { params: { query } } as any);
    },
    signupAgent(body) {
      return client.POST("/v1/auth/agent" as any, { body } as any);
    },
    agentClaim(body) {
      return client.POST("/v1/auth/agent/claim" as any, { body } as any);
    },
    agentClaimComplete(body) {
      return client.POST("/v1/auth/agent/claim/complete" as any, { body } as any);
    },
    agentRevoke() {
      return client.POST("/v1/auth/agent/revoke" as any, {} as any);
    },
    confirmVerification(body) {
      return client.POST("/v1/auth/verify/confirm" as any, { body } as any);
    },
    requestVerification(body) {
      return client.POST("/v1/auth/verify/request" as any, { body } as any);
    },
    checkSpec(body) {
      return client.POST("/v1/check" as any, { body } as any);
    },
    getCheckRules() {
      return client.GET("/v1/check/rules" as any, {} as any);
    },
    updateCheckRules(body) {
      return client.PUT("/v1/check/rules" as any, { body } as any);
    },
    addClipBroll(body) {
      return client.POST("/v1/clips/broll" as any, { body } as any);
    },
    addClipCaptions(body) {
      return client.POST("/v1/clips/captions" as any, { body } as any);
    },
    generateClips(body) {
      return client.POST("/v1/clips/generate" as any, { body } as any);
    },
    checkCompliancePrompt(body) {
      return client.POST("/v1/compliance/prompt" as any, { body } as any);
    },
    checkComplianceVideo(body) {
      return client.POST("/v1/compliance/video" as any, { body } as any);
    },
    getCheckoutStatus(query) {
      return client.GET("/v1/credits/status" as any, { params: { query } } as any);
    },
    createDisclaimer(body) {
      return client.POST("/v1/disclaimer" as any, { body } as any);
    },
    listOrGetDistributionClips(query) {
      return client.GET("/v1/distribution/clips" as any, { params: { query } } as any);
    },
    getDistributionJob(query) {
      return client.GET("/v1/distribution/jobs" as any, { params: { query } } as any);
    },
    extractMedia(body) {
      return client.POST("/v1/extract" as any, { body } as any);
    },
    getInfo() {
      return client.GET("/v1/info" as any, {} as any);
    },
    getJob(query) {
      return client.GET("/v1/jobs" as any, { params: { query } } as any);
    },
    createOverlay(body) {
      return client.POST("/v1/overlay" as any, { body } as any);
    },
    createPost(body) {
      return client.POST("/v1/posts" as any, { body } as any);
    },
    updatePost(body, query) {
      return client.PUT("/v1/posts" as any, { body, params: { query } } as any);
    },
    listOrGetPosts(query) {
      return client.GET("/v1/posts" as any, { params: { query } } as any);
    },
    deletePost(query) {
      return client.DELETE("/v1/posts" as any, { params: { query } } as any);
    },
    getPricing() {
      return client.GET("/v1/pricing" as any, {} as any);
    },
    createEditorProject(body) {
      return client.POST("/v1/projects" as any, { body } as any);
    },
    updateEditorProject(body, query) {
      return client.PUT("/v1/projects" as any, { body, params: { query } } as any);
    },
    listOrGetEditorProjects(query) {
      return client.GET("/v1/projects" as any, { params: { query } } as any);
    },
    deleteEditorProject(query) {
      return client.DELETE("/v1/projects" as any, { params: { query } } as any);
    },
    createReference(body) {
      return client.POST("/v1/references" as any, { body } as any);
    },
    updateReference(body, query) {
      return client.PUT("/v1/references" as any, { body, params: { query } } as any);
    },
    listOrGetReferences(query) {
      return client.GET("/v1/references" as any, { params: { query } } as any);
    },
    deleteReference(query) {
      return client.DELETE("/v1/references" as any, { params: { query } } as any);
    },
    scrapeInstagramPost(body) {
      return client.POST("/v1/scrape/instagram/post" as any, { body } as any);
    },
    scrapeInstagramPostComments(body) {
      return client.POST("/v1/scrape/instagram/post/comments" as any, { body } as any);
    },
    scrapeInstagramProfile(body) {
      return client.POST("/v1/scrape/instagram/profile" as any, { body } as any);
    },
    scrapeInstagramUserPosts(body) {
      return client.POST("/v1/scrape/instagram/user/posts" as any, { body } as any);
    },
    scrapeInstagramUserReels(body) {
      return client.POST("/v1/scrape/instagram/user/reels" as any, { body } as any);
    },
    scrapeTikTokProfile(body) {
      return client.POST("/v1/scrape/tiktok/profile" as any, { body } as any);
    },
    scrapeTikTokProfileVideos(body) {
      return client.POST("/v1/scrape/tiktok/profile/videos" as any, { body } as any);
    },
    scrapeTikTokSearchUsers(body) {
      return client.POST("/v1/scrape/tiktok/search/users" as any, { body } as any);
    },
    scrapeTikTokTrending(body) {
      return client.POST("/v1/scrape/tiktok/trending" as any, { body } as any);
    },
    scrapeTikTokVideo(body) {
      return client.POST("/v1/scrape/tiktok/video" as any, { body } as any);
    },
    scrapeTikTokVideoComments(body) {
      return client.POST("/v1/scrape/tiktok/video/comments" as any, { body } as any);
    },
    scrapeTikTokVideoTranscript(body) {
      return client.POST("/v1/scrape/tiktok/video/transcript" as any, { body } as any);
    },
    createSubscription(body) {
      return client.POST("/v1/subscribe" as any, { body } as any);
    },
    transcribeMedia(body) {
      return client.POST("/v1/transcribe" as any, { body } as any);
    },
    uploadFile() {
      return client.POST("/v1/upload" as any, {} as any);
    },
    uploadFromUrl(body) {
      return client.POST("/v1/upload/url" as any, { body } as any);
    },
    getUsage() {
      return client.GET("/v1/usage" as any, {} as any);
    },
    addVideo(body) {
      return client.POST("/v1/videos/add" as any, { body } as any);
    },
    downloadInstagramVideo(body) {
      return client.POST("/v1/videos/download/instagram" as any, { body } as any);
    },
    downloadTikTokVideo(body) {
      return client.POST("/v1/videos/download/tiktok" as any, { body } as any);
    },
    watchMedia(body) {
      return client.POST("/v1/watch" as any, { body } as any);
    },
  };
}
